### ISSUE TITLE
Bug: Self-Deployed - API Key

### ISSUE THREAD

**Issue by argidenise** [ztjhz/FreeChatGPT#77]
Hello!

If I enter my OpenAI API key on the Use your own API key, the API endpoint does not change to official OpenAI endpoint instead it stays on https://chatgpt-api.shn.hk/v1/. 

You can reproduce this issue easily on localhost.

**Comment by argidenise** [comment]
![Screenshot (190)](https://user-images.githubusercontent.com/127620618/225003534-37bb9273-060a-4a5e-88d4-4fec20373608.png)

![Screenshot (189)](https://user-images.githubusercontent.com/127620618/225003641-851d750d-b0dc-434d-b82c-e17d1c868e28.png)

I use NPM.

**Comment by ztjhz** [comment]
If you've entered your OpenAI API key in the "Use your own API key" field and you want to switch to using the official OpenAI endpoint instead of the default endpoint, you can do so by clicking on the dropdown menu next to "API Endpoint" and selecting "OpenAI API".

Once you've selected this option, any requests you make will be sent directly to OpenAI's servers using your personal API key. It's worth noting that if you're in an area where accessing chatgpt is blocked, you may need to use the default endpoint with your API key, as this option routes your requests through a proxy, allowing you to bypass any blocks.

If you want to use a custom API endpoint that you have hosted yourself, you can do so by selecting the "Custom Endpoint" checkbox above the "API Endpoint" dropdown menu. Once you've selected this option, you'll be prompted to enter the URL for your custom endpoint.

**Comment by argidenise** [comment]
Thank you so much for the info. On my part, I was expecting that when I enter my API key it will automatically switched to OpenAI API endpoint.
